language: python
sudo: true
python:
- 3.6
services:
- mysql
branches:
  only:
  - develop
install:
- pip install --upgrade pip
- pip install -r requirements.txt
- pip install flake8
- pip install coveralls
before_script:
- flake8 tp-screening
- python manage.py makemigrations
- python manage.py migrate
- mysql -e 'create database edc character set utf8;'
script:
- coverage run --source=tp-subject-validators manage.py test
after_success:
- coveralls
